"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
import os
import shutil
import subprocess

sys.setrecursionlimit(10000)

# Monkey patch importlib.resources for py2app on Python 3.7
try:
    import importlib.resources
    if not hasattr(importlib.resources, 'files'):
        import importlib_resources
        importlib.resources.files = importlib_resources.files
except ImportError:
    pass

APP = ['desktop_app.py']

def _prepare_resource_staging():
    project_root = os.path.dirname(os.path.abspath(__file__))
    staging_root = os.path.join(project_root, "build", "resource_staging")
    os.makedirs(staging_root, exist_ok=True)

    src_memory_dir = os.path.join(project_root, "memory")
    dst_memory_dir = os.path.join(staging_root, "memory")
    if os.path.exists(dst_memory_dir):
        shutil.rmtree(dst_memory_dir)
    if os.path.isdir(src_memory_dir):
        for root, dirs, files in os.walk(src_memory_dir):
            dirs[:] = [d for d in dirs if isinstance(d, str) and d not in ("__pycache__",) and not d.startswith(".")]
            rel = os.path.relpath(root, src_memory_dir)
            out_dir = dst_memory_dir if rel == "." else os.path.join(dst_memory_dir, rel)
            os.makedirs(out_dir, exist_ok=True)
            for name in files:
                if not isinstance(name, str) or name.startswith(".") or not name.endswith(".md"):
                    continue
                src = os.path.join(root, name)
                dst = os.path.join(out_dir, name)
                if os.path.isfile(src):
                    shutil.copy2(src, dst)

    return dst_memory_dir

STAGED_MEMORY_DIR = _prepare_resource_staging()
_base_prefix = getattr(sys, "base_prefix", sys.prefix)
_framework_candidates = [
    os.path.join(_base_prefix, "lib", "libffi.8.dylib"),
    os.path.join(_base_prefix, "lib", "libssl.1.1.dylib"),
    os.path.join(_base_prefix, "lib", "libcrypto.1.1.dylib"),
]
_extra_frameworks = [p for p in _framework_candidates if os.path.exists(p)]
OPTIONS = {
    'iconfile': 'assets/app.icns',
    'compressed': True,
    'optimize': 2,
    'strip': True,
    'resources': ['frontend', 'assets', STAGED_MEMORY_DIR],
    'frameworks': _extra_frameworks,
    'plist': {
        'CFBundleName': 'Generic Agent',
        'CFBundleDisplayName': 'Generic Agent',
        'CFBundleGetInfoString': "Generic Agent Desktop App",
        'CFBundleIdentifier': "com.genericagent.desktop",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2026, Generic Agent, All Rights Reserved",
        'LSUIElement': False, # Show dock icon
    },
    'includes': [
        'uvicorn', 'fastapi', 'requests', 'bs4', 'soupsieve',
        'uvicorn.loops', 'uvicorn.loops.asyncio',
        'uvicorn.protocols', 'uvicorn.protocols.http', 'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl', 'uvicorn.protocols.http.httptools_impl',
        'uvicorn.lifespan', 'uvicorn.lifespan.off',
        'api_server', 'agentmain', 'sidercall', 'agent_loop', 'ga', 'simphtml',
        'PyQt5.QtWidgets', 'PyQt5.QtWebEngineWidgets', 'PyQt5.QtWebEngineCore', 'PyQt5.QtWebEngine', 'PyQt5.QtWebChannel',
        'PyQtWebEngine',
        'PyQt5.QtCore', 'PyQt5.QtGui',
        'anyio', 'anyio._backends', 'anyio._backends._asyncio', 'sniffio', 'starlette'
    ],
    'excludes': [
        'mykey',
        'streamlit', 'webview', 'pywebview', 'pytest', 'unittest',
        'matplotlib', 'mpl_toolkits', 'numpy', 'scipy', 'pandas', 'sympy',
        'sklearn', 'torch', 'tensorflow', 'jax', 'jaxlib',
        'cv2', 'PIL', 'Pillow',
        'IPython', 'jupyter', 'notebook',
    ],
}

def _codesign_app(app_path):
    if not os.path.exists(app_path):
        return
    if shutil.which("codesign") is None:
        return
    frameworks_dir = os.path.join(app_path, "Contents", "Frameworks")
    if os.path.isdir(frameworks_dir):
        for name in os.listdir(frameworks_dir):
            if not name.endswith(".dylib"):
                continue
            subprocess.run(
                ["codesign", "--force", "--sign", "-", "--timestamp=none", os.path.join(frameworks_dir, name)],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )

    subprocess.run(
        ["codesign", "--force", "--deep", "--sign", "-", "--timestamp=none", app_path],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    subprocess.run(
        ["codesign", "--verify", "--deep", "--strict", "--verbose=2", app_path],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

def _remove_ds_store(root):
    for dirpath, dirnames, filenames in os.walk(root):
        if ".DS_Store" in filenames:
            try:
                os.remove(os.path.join(dirpath, ".DS_Store"))
            except Exception:
                pass

def _prune_bundle(app_path):
    resources_root = os.path.join(app_path, "Contents", "Resources")
    if not os.path.isdir(resources_root):
        return
    for lib_dir in (
        os.path.join(resources_root, "lib", "python3.11"),
        os.path.join(resources_root, "lib", "python3.10"),
        os.path.join(resources_root, "lib", "python3.9"),
        os.path.join(resources_root, "lib", "python3.8"),
        os.path.join(resources_root, "lib", "python3.7"),
    ):
        tornado_test = os.path.join(lib_dir, "tornado", "test")
        if os.path.isdir(tornado_test):
            shutil.rmtree(tornado_test, ignore_errors=True)

    for lib_dir in (
        os.path.join(resources_root, "lib", "python3.11"),
        os.path.join(resources_root, "lib", "python3.10"),
        os.path.join(resources_root, "lib", "python3.9"),
        os.path.join(resources_root, "lib", "python3.8"),
        os.path.join(resources_root, "lib", "python3.7"),
    ):
        dangling_site = os.path.join(lib_dir, "site.pyo")
        if os.path.islink(dangling_site) and not os.path.exists(dangling_site):
            try:
                os.unlink(dangling_site)
            except Exception:
                pass

try:
    from py2app.build_app import py2app as _py2app

    class py2app(_py2app):
        def run(self):
            super().run()
            project_root = os.path.dirname(os.path.abspath(__file__))
            dist_root = getattr(self, "dist_dir", None) or "dist"
            if not os.path.isabs(dist_root):
                dist_root = os.path.join(project_root, dist_root)
            dist_root = os.path.abspath(dist_root)
            _remove_ds_store(dist_root)
            app_path = os.path.join(dist_root, "Generic Agent.app")
            _prune_bundle(app_path)
            _codesign_app(app_path)
except Exception:
    py2app = None

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    cmdclass={"py2app": py2app} if py2app else None,
)
