"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
import os
import shutil
import subprocess

sys.setrecursionlimit(10000)

# Monkey patch importlib.resources for py2app on Python 3.7
try:
    import importlib.resources
    if not hasattr(importlib.resources, 'files'):
        import importlib_resources
        importlib.resources.files = importlib_resources.files
except ImportError:
    pass

BACKEND_ROOT = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(BACKEND_ROOT)
APP = [os.path.join(BACKEND_ROOT, 'desktop_app.py')]

def _prepare_resource_staging():
    staging_root = os.path.join(BACKEND_ROOT, "build", "resource_staging")
    os.makedirs(staging_root, exist_ok=True)

    def _stage_tree(name, src_root, allowed_suffixes=None, ignored_dirs=None, ignored_files=None):
        dst_root = os.path.join(staging_root, name)
        if os.path.exists(dst_root):
            shutil.rmtree(dst_root)
        if not os.path.isdir(src_root):
            return dst_root
        ignored_dirs = set(ignored_dirs or ())
        ignored_files = set(ignored_files or ())
        for root, dirs, files in os.walk(src_root):
            dirs[:] = [
                d for d in dirs
                if isinstance(d, str)
                and d not in ("__pycache__",)
                and d not in ignored_dirs
                and not d.startswith(".")
            ]
            rel = os.path.relpath(root, src_root)
            out_dir = dst_root if rel == "." else os.path.join(dst_root, rel)
            os.makedirs(out_dir, exist_ok=True)
            for entry in files:
                if (
                    not isinstance(entry, str)
                    or entry in ignored_files
                    or entry.startswith(".")
                    or entry.endswith((".pyc", ".pyo"))
                ):
                    continue
                if allowed_suffixes and not entry.endswith(allowed_suffixes):
                    continue
                src = os.path.join(root, entry)
                dst = os.path.join(out_dir, entry)
                if os.path.isfile(src):
                    shutil.copy2(src, dst)
        return dst_root

    staged_paths = []
    staged_paths.append(_stage_tree("memory", os.path.join(REPO_ROOT, "memory")))
    staged_paths.append(
        _stage_tree(
            "ga_config",
            os.path.join(BACKEND_ROOT, "ga_config"),
            ignored_dirs=("ga_config", "temp"),
            ignored_files=("mykey.json", "mykey.py"),
        )
    )
    for mykey_name in ("mykey.json", "mykey.py"):
        mykey_src = os.path.join(BACKEND_ROOT, mykey_name)
        if os.path.isfile(mykey_src):
            shutil.copy2(mykey_src, os.path.join(staging_root, "ga_config", mykey_name))
    return staged_paths

STAGED_RESOURCE_DIRS = _prepare_resource_staging()
_base_prefix = getattr(sys, "base_prefix", sys.prefix)
_framework_candidates = [
    os.path.join(_base_prefix, "lib", "libffi.8.dylib"),
    os.path.join(_base_prefix, "lib", "libssl.1.1.dylib"),
    os.path.join(_base_prefix, "lib", "libcrypto.1.1.dylib"),
]
_extra_frameworks = [p for p in _framework_candidates if os.path.exists(p)]
OPTIONS = {
    'iconfile': os.path.join(BACKEND_ROOT, 'assets', 'app.icns'),
    'compressed': True,
    'optimize': 2,
    'strip': True,
    'resources': [
        os.path.join(REPO_ROOT, 'frontend'),
        os.path.join(BACKEND_ROOT, 'assets'),
    ] + STAGED_RESOURCE_DIRS,
    'frameworks': _extra_frameworks,
    'plist': {
        'CFBundleName': 'A3Agent',
        'CFBundleDisplayName': 'A3Agent',
        'CFBundleGetInfoString': "A3Agent Desktop App",
        'CFBundleIdentifier': "com.guofang.a3agent.desktop",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2026, A3Agent, All Rights Reserved",
        'LSUIElement': False, # Show dock icon
    },
    'includes': [
        'uvicorn', 'fastapi', 'requests', 'bs4', 'soupsieve',
        'uvicorn.loops', 'uvicorn.loops.asyncio',
        'uvicorn.protocols', 'uvicorn.protocols.http', 'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl', 'uvicorn.protocols.http.httptools_impl',
        'uvicorn.lifespan', 'uvicorn.lifespan.off',
        'api_server', 'agentmain', 'sidercall', 'agent_loop', 'ga', 'simphtml',
        'PyQt5.QtWidgets', 'PyQt5.QtWebEngineWidgets', 'PyQt5.QtWebEngineCore', 'PyQt5.QtWebEngine', 'PyQt5.QtWebChannel',
        'PyQtWebEngine',
        'PyQt5.QtCore', 'PyQt5.QtGui',
        'anyio', 'anyio._backends', 'anyio._backends._asyncio', 'sniffio', 'starlette'
    ],
    'excludes': [
        'mykey',
        'streamlit', 'webview', 'pywebview', 'pytest', 'unittest',
        'matplotlib', 'mpl_toolkits', 'numpy', 'scipy', 'pandas', 'sympy',
        'sklearn', 'torch', 'tensorflow', 'jax', 'jaxlib',
        'cv2', 'PIL', 'Pillow',
        'IPython', 'jupyter', 'notebook',
    ],
}

def _codesign_app(app_path):
    if not os.path.exists(app_path):
        return
    if shutil.which("codesign") is None:
        return

    def _sign_target(target):
        subprocess.run(
            ["codesign", "--force", "--sign", "-", "--timestamp=none", target],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    frameworks_dir = os.path.join(app_path, "Contents", "Frameworks")
    if os.path.isdir(frameworks_dir):
        for name in os.listdir(frameworks_dir):
            target = os.path.join(frameworks_dir, name)
            if os.path.islink(target):
                continue
            if os.path.isdir(target) and not name.endswith(".framework"):
                continue
            if os.path.isfile(target) and not name.endswith(".dylib"):
                continue
            _sign_target(target)
    macos_dir = os.path.join(app_path, "Contents", "MacOS")
    if os.path.isdir(macos_dir):
        for name in os.listdir(macos_dir):
            target = os.path.join(macos_dir, name)
            if not os.path.isfile(target) or os.path.islink(target):
                continue
            _sign_target(target)

    subprocess.run(
        ["codesign", "--force", "--deep", "--sign", "-", "--timestamp=none", app_path],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    subprocess.run(
        ["codesign", "--verify", "--deep", "--strict", "--verbose=2", app_path],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

def _remove_ds_store(root):
    for dirpath, dirnames, filenames in os.walk(root):
        if ".DS_Store" in filenames:
            try:
                os.remove(os.path.join(dirpath, ".DS_Store"))
            except Exception:
                pass

def _prune_bundle(app_path):
    resources_root = os.path.join(app_path, "Contents", "Resources")
    if not os.path.isdir(resources_root):
        return
    for lib_dir in (
        os.path.join(resources_root, "lib", "python3.11"),
        os.path.join(resources_root, "lib", "python3.10"),
        os.path.join(resources_root, "lib", "python3.9"),
        os.path.join(resources_root, "lib", "python3.8"),
        os.path.join(resources_root, "lib", "python3.7"),
    ):
        tornado_test = os.path.join(lib_dir, "tornado", "test")
        if os.path.isdir(tornado_test):
            shutil.rmtree(tornado_test, ignore_errors=True)

    for lib_dir in (
        os.path.join(resources_root, "lib", "python3.11"),
        os.path.join(resources_root, "lib", "python3.10"),
        os.path.join(resources_root, "lib", "python3.9"),
        os.path.join(resources_root, "lib", "python3.8"),
        os.path.join(resources_root, "lib", "python3.7"),
    ):
        dangling_site = os.path.join(lib_dir, "site.pyo")
        if os.path.islink(dangling_site) and not os.path.exists(dangling_site):
            try:
                os.unlink(dangling_site)
            except Exception:
                pass

try:
    from py2app.build_app import py2app as _py2app

    class py2app(_py2app):
        def run(self):
            super().run()
            dist_root = getattr(self, "dist_dir", None) or "dist"
            if not os.path.isabs(dist_root):
                dist_root = os.path.join(BACKEND_ROOT, dist_root)
            dist_root = os.path.abspath(dist_root)
            _remove_ds_store(dist_root)
            app_path = os.path.join(dist_root, "A3Agent.app")
            _prune_bundle(app_path)
            _codesign_app(app_path)
except Exception:
    py2app = None

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    cmdclass={"py2app": py2app} if py2app else None,
)
